particles:
  '1':
    color: random
    height: 6.0
    mass: 0.5
    n: 50
    radius: 3.0
    shape: Circle
    width: 6.0
  '2':
    color: random
    height: 20.0
    mass: 2.0
    n: 50
    radius: 10.0
    shape: Circle
    width: 20.0
  '3':
    color: random
    height: 10.0
    mass: 1.0
    n: 100
    radius: 5.0
    shape: Circle
    width: 10.0
walls: {}
