particles:
  '2':
    color: random
    height: 80.0
    mass: 5.0
    n: 3
    radius: 40.0
    shape: Circle
    width: 80.0
  '3':
    color: black
    height: 6.0
    mass: 0.5
    n: 50
    radius: 3.0
    shape: Circle
    width: 6.0
walls:
  '1':
    p0x: 100.0
    p0y: 100.0
    p1x: 200.0
    p1y: 100.0
  '2':
    p0x: 200.0
    p0y: 100.0
    p1x: 200.0
    p1y: 200.0
  '5':
    p0x: 300.0
    p0y: 300.0
    p1x: 400.0
    p1y: 400.0
  '6':
    p0x: 400.0
    p0y: 400.0
    p1x: 300.0
    p1y: 500.0
  '7':
    p0x: 300.0
    p0y: 500.0
    p1x: 200.0
    p1y: 400.0
  '8':
    p0x: 200.0
    p0y: 400.0
    p1x: 300.0
    p1y: 300.0
