particles:
  group1:
    color: black
    height: 10.0
    mass: 1.0
    n: 10
    radius: 5.0
    shape: Circle
    width: 10.0
  group2:
    color: green
    height: 10.0
    mass: 20.0
    n: 1
    radius: 50.0
    shape: Circle
    width: 10.0
