particles:
  group1:
    n: 100
    color: random
    radius: 5.0
    mass: 1.0
    shape: "Circle"
    width: 10.0
    height: 10.0
  group2:
    n: 3
    color: random
    radius: 40.0
    mass: 5.0
    shape: "Circle"
    width: 80.0
    height: 80.0
  group3:
    n: 50
    color: black
    radius: 3.0
    mass: 0.5
    shape: "Circle"
    width: 6.0
    height: 6.0
walls:
  line1:
    p0x: 100.0
    p0y: 100.0
    p1x: 200.0
    p1y: 100.0
  line2:
    p0x: 200.0
    p0y: 100.0
    p1x: 200.0
    p1y: 200.0
  line3:
    p0x: 200.0
    p0y: 200.0
    p1x: 100.0
    p1y: 200.0
  line5:
    p0x: 300.0
    p0y: 300.0
    p1x: 400.0
    p1y: 400.0
  line6:
    p0x: 400.0
    p0y: 400.0
    p1x: 300.0
    p1y: 500.0